name: Publish Docker image

on:
  push:
    branches: ['ml-pipeline']

jobs:
  push_to_ACR:
    name: Push to Azure Container Registry
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repo
        uses: actions/checkout@v4
    
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: deepiaacr.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD}}
      
      - run: |
          docker build --no-cache -t deepiaacr.azurecr.io/deeptargetfront:${{ github.sha }} .
          docker push deepiaacr.azurecr.io/deeptargetfront:${{ github.sha }}